# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: comment_continuation.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'comment_continuation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63omment_continuation.proto\"\xae\x04\n\x0c\x43ontinuation\x12-\n\x08video_id\x18\x02 \x01(\x0b\x32\x1b.Continuation.VideoIdSubMsg\x12\r\n\x05int_3\x18\x03 \x01(\x11\x12\x36\n\x0c\x63ontinuation\x18\x06 \x01(\x0b\x32 .Continuation.ContinuationSubMsg\x1a\x1e\n\rVideoIdSubMsg\x12\r\n\x05value\x18\x02 \x01(\t\x1a%\n\tsomething\x12\x10\n\x03idk\x18\x01 \x01(\rH\x00\x88\x01\x01\x42\x06\n\x04_idk\x1a%\n\x14SubMesssage_16SubMsg\x12\r\n\x05int_1\x18\x01 \x01(\r\x1a\xe0\x01\n\rContextSubMsg\x12\x11\n\tthread_id\x18\x02 \x01(\t\x12*\n\tsomething\x18\x04 \x01(\x0b\x32\x17.Continuation.something\x12\x13\n\x0buploader_id\x18\x05 \x01(\t\x12\x10\n\x08video_id\x18\x06 \x01(\t\x12\x12\n\nsort_maybe\x18\x08 \x01(\x11\x12\x19\n\x11max_replies_maybe\x18\t \x01(\r\x12:\n\x0esub_message_16\x18\x10 \x01(\x0b\x32\".Continuation.SubMesssage_16SubMsg\x1aW\n\x12\x43ontinuationSubMsg\x12,\n\x07\x63ontext\x18\x03 \x01(\x0b\x32\x1b.Continuation.ContextSubMsg\x12\x13\n\x0btype_string\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comment_continuation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTINUATION']._serialized_start=31
  _globals['_CONTINUATION']._serialized_end=589
  _globals['_CONTINUATION_VIDEOIDSUBMSG']._serialized_start=165
  _globals['_CONTINUATION_VIDEOIDSUBMSG']._serialized_end=195
  _globals['_CONTINUATION_SOMETHING']._serialized_start=197
  _globals['_CONTINUATION_SOMETHING']._serialized_end=234
  _globals['_CONTINUATION_SUBMESSSAGE_16SUBMSG']._serialized_start=236
  _globals['_CONTINUATION_SUBMESSSAGE_16SUBMSG']._serialized_end=273
  _globals['_CONTINUATION_CONTEXTSUBMSG']._serialized_start=276
  _globals['_CONTINUATION_CONTEXTSUBMSG']._serialized_end=500
  _globals['_CONTINUATION_CONTINUATIONSUBMSG']._serialized_start=502
  _globals['_CONTINUATION_CONTINUATIONSUBMSG']._serialized_end=589
# @@protoc_insertion_point(module_scope)
